name: Daily Commit

on:
  schedule:
    # Runs daily at 12:00 UTC (adjust the cron syntax as needed)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit with email 22f2000409@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "22f2000409@ds.study.iitm.ac.in"
          date >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily commit by GitHub Actions"
          git push
